#!/bin/sh /etc/rc.common
#Copyright (C) 20190805 wulishui <wulishui@gmail.com>
#20190805-202105025

START=99
USE_PROCD=1

start_instance() {
	procd_open_instance
	procd_set_param command /usr/bin/cowbpingd
	procd_set_param respawn
	procd_set_param stderr 1
	procd_close_instance
}

start_service() {
	stop_service
	[ -f /var/lock/cowbping ] && exit
	enabled=$(uci get cowbping.cowbping.enabled 2>/dev/null)
	if [ "$enabled" == 1 ]; then
		touch /var/lock/cowbping
		cat /dev/null >/tmp/log/cowbping.log
		kill -9 $(busybox ps -w | grep 'cowbpingd' | grep -v 'grep' | awk '{print $1}')
		start_instance
		rm -f /var/lock/cowbping
	fi
}

service_triggers() {
	procd_add_reload_trigger 'cowbping'
}

stop_service() {
	kill -9 $(busybox ps -w | grep 'cbp_cmd' | grep -v 'grep' | awk '{print $1}') >/dev/null 2>&1
}

restart() {
	stop_service
	start_service
}
