#!/bin/sh

uci -q batch <<-EOF >/dev/null
	delete ucitrack.@cowbbonding[-1]
	add ucitrack cowbbonding
	set ucitrack.@cowbbonding[-1].init=cowbbonding
	commit ucitrack
EOF

uci delete firewall.cowbbonding
uci set firewall.cowbbonding=include
uci set firewall.cowbbonding.type=script
uci set firewall.cowbbonding.path=/etc/cowbbonding.include
# uci set firewall.cowbbonding.reload=1
uci commit firewall

mkdir /etc/cowbbonding
[ -s /etc/cowbbonding/list.cfg ] || echo "A0:11:22:33:44:55 192.168.18.244 Example-1" >> /etc/cowbbonding/list.cfg

echo "/etc/cowbbonding/list.cfg" >> /etc/sysupgrade.conf

rm -f /tmp/luci-indexcache
exit 0
