#!/bin/bash

cd lede

(
    cd package
    git clone https://github.com/tuanqing/install-program
    # git clone https://github.com/tuanqing/openwrt-mentohust
    # git clone https://github.com/tuanqing/luci-app-mentohust
    # git clone https://github.com/jerrykuku/luci-app-jd-dailybonus
    # git clone https://github.com/jerrykuku/luci-app-ttnode
    git clone https://github.com/jerrykuku/luci-theme-argon -b 18.06
    git clone https://github.com/jerrykuku/luci-app-argon-config
#     git clone https://github.com/lisaac/luci-lib-docker
#     git clone https://github.com/lisaac/luci-app-dockerman

#     sed -i 's/+docker-ce/+docker +dockerd/' luci-app-dockerman/applications/luci-app-dockerman/Makefile

    rm -rf libs/nettle
    rm -rf lean/{samba4,luci-app-samba4,luci-app-ttyd,luci-theme-argon,luci-lib-docker}
    # svn co https://github.com/Lienol/openwrt/trunk/package/libs/{libaudit,libsemanage,musl-fts,nettle} libs
    git clone https://github.com/Lienol/openwrt -b main lienol-openwrt
    cp -r lienol-openwrt/package/libs/{libaudit,libsemanage,musl-fts,nettle} libs/
    rm -rf lienol-openwrt
)

cat >feeds.conf.default <<-EOF
src-git luci https://github.com/Lienol/openwrt-luci.git;18.06
src-git packages https://github.com/Lienol/openwrt-packages.git;main
src-git routing https://git.openwrt.org/feed/routing.git
src-git telephony https://git.openwrt.org/feed/telephony.git
src-git helloworld https://github.com/fw876/helloworld.git
EOF

./scripts/feeds update -a
./scripts/feeds install -a

# sed -i '/+libmount/d' feeds/packages/utils/btrfs-progs/Makefile

git apply ../.github/patches/{0001*,0002*}.patch --directory=feeds/luci
(
    cd feeds/luci/modules/luci-mod-admin-full/luasrc/view/admin_status
    mv index.htm index.htm.old
    cp index_arm.htm index.htm
)

zzz="package/lean/default-settings/files/zzz-default-settings"
sed -i 's/samba/samba4/' $zzz
sed -i "/openwrt_luci/i sed -i '/Lienol/d' /etc/opkg/distfeeds.conf" $zzz
sed -i "/openwrt_luci/i sed -i '/helloworld/d' /etc/opkg/distfeeds.conf" $zzz

packages=" \
brcmfmac-firmware-43430-sdio brcmfmac-firmware-43455-sdio kmod-brcmfmac wpad \
kmod-fs-ext4 kmod-fs-vfat kmod-fs-exfat dosfstools e2fsprogs ntfs-3g \
kmod-usb2 kmod-usb3 kmod-usb-storage kmod-usb-storage-extras kmod-usb-storage-uas \
kmod-usb-net kmod-usb-net-asix-ax88179 kmod-usb-net-rtl8150 kmod-usb-net-rtl8152 \
blkid lsblk parted fdisk cfdisk losetup resize2fs tune2fs pv unzip \
lscpu htop iperf3 curl lm-sensors python3 install-program
"
sed -i '/FEATURES+=/ { s/cpiogz //; s/ext4 //; s/ramdisk //; s/squashfs //; }' \
    target/linux/armvirt/Makefile
for x in $packages; do
    sed -i "/DEFAULT_PACKAGES/ s/$/ $x/" target/linux/armvirt/Makefile
done

rm -f package/lean/shadowsocksr-libev/patches/0002-Revert-verify_simple-and-auth_simple.patch
sed -i '383,393 d' package/lean/shadowsocksr-libev/patches/0001-Add-ss-server-and-ss-check.patch
sed -i 's/PKG_RELEASE:=5/PKG_RELEASE:=6/' package/lean/shadowsocksr-libev/Makefile
sed -i '/PKG_SOURCE_VERSION:=/d' package/lean/shadowsocksr-libev/Makefile
sed -i '/PKG_SOURCE_URL/a PKG_SOURCE_VERSION:=4799b312b8244ec067b8ae9ba4b85c877858976c' \
    package/lean/shadowsocksr-libev/Makefile

# sed -i 's/ipaddr:-"192.168.1.1"/ipaddr:-"192.168.1.10"/' package/base-files/files/bin/config_generate

cat >.config <<-EOF
## target
CONFIG_TARGET_armvirt=y
CONFIG_TARGET_armvirt_64=y
CONFIG_TARGET_armvirt_64_Default=y
## luci app
CONFIG_PACKAGE_luci-app-adbyby-plus=y
CONFIG_PACKAGE_luci-app-aria2=y
CONFIG_PACKAGE_luci-app-cifs-mount=y
CONFIG_PACKAGE_luci-app-samba4=y
CONFIG_PACKAGE_luci-app-ttyd=y
# CONFIG_PACKAGE_luci-app-mentohust=y
# CONFIG_PACKAGE_luci-app-jd-dailybonus=y
# CONFIG_PACKAGE_luci-app-ttnode=y
# CONFIG_PACKAGE_luci-app-dockerman=y
CONFIG_PACKAGE_luci-app-argon-config=y
## luci theme
CONFIG_PACKAGE_luci-theme-bootstrap-mod=y
CONFIG_PACKAGE_luci-theme-argon=y
## remove
# CONFIG_UnblockNeteaseMusic_NodeJS is not set
# CONFIG_PACKAGE_luci-app-webadmin is not set
## others
CONFIG_BRCMFMAC_SDIO=y
CONFIG_LUCI_LANG_en=y
EOF

make defconfig
cat .config
