include $(TOPDIR)/rules.mk

LUCI_TITLE:=LuCI support for white or black list
LUCI_DEPENDS:=
LUCI_PKGARCH:=all

PKG_VERSION:=2.1.1-20210731

include $(TOPDIR)/feeds/luci/luci.mk

# call BuildPackage - OpenWrt buildroot signature
