#!/bin/sh

uci -q batch <<-EOF >/dev/null
	delete ucitrack.@cowbping[-1]
	add ucitrack cowbping
	set ucitrack.@cowbping[-1].init=cowbping
	commit ucitrack
EOF

touch /etc/config/cbp_cmd

rm -f /tmp/luci-indexcache
exit 0
